### ISSUE TITLE
Getting a traceback when generating helptext

### ISSUE THREAD

**Issue by jherrman** [fedora-copr/logdetective#86]
I'm getting the following error message when running `logdetective --help` :

***
Traceback (most recent call last):
  File "/usr/bin/logdetective", line 5, in <module>
    from logdetective.logdetective import main
  File "/usr/lib/python3.12/site-packages/logdetective/logdetective.py", line 6, in <module>
    from logdetective.utils import process_log, initialize_model, retrieve_log_content, format_snippets
  File "/usr/lib/python3.12/site-packages/logdetective/utils.py", line 7, in <module>
    from llama_cpp import Llama
  File "/usr/lib64/python3.12/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/usr/lib64/python3.12/site-packages/llama_cpp/llama_cpp.py", line 1434, in <module>
    @ctypes_function(
     ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/llama_cpp/llama_cpp.py", line 122, in decorator
    func = getattr(lib, name)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 392, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 397, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/lib64/libllama.so: undefined symbol: llama_model_apply_lora_from_file
***

System: Fedora 40
Hardware: ThinkPad T14

**Comment by TomasTomecek** [comment]
Finally figured it out, thanks everyone for help!

https://src.fedoraproject.org/rpms/python-llama-cpp-python/pull-request/9#request_diff

Will merge, build and do a bodhi update soon.

Smoke-tested in a f40 container and all worked well:
```
[root@1f5dc2461be6 src]# logdetective --help
usage: logdetective [-h] [-M MODEL] [-F FILENAME_SUFFIX] [-S SUMMARIZER] [-N N_LINES] [-C N_CLUSTERS] [-v] [-q] file

positional arguments:
  file                  The URL or path to the log file to be analyzed.

options:
  -h, --help            show this help message and exit
  -M MODEL, --model MODEL
                        The path or Hugging Face name of the language model for analysis.
  -F FILENAME_SUFFIX, --filename_suffix FILENAME_SUFFIX
                        Suffix of the model file name to be retrieved from Hugging Face. Makes sense only if the model is specified with Hugging Face name.
  -S SUMMARIZER, --summarizer SUMMARIZER
                        Choose between LLM and Drain template miner as the log summarizer. LLM must be specified as path to a model, URL or local file.
  -N N_LINES, --n_lines N_LINES
                        The number of lines per chunk for LLM analysis. This only makes sense when you are summarizing with LLM.
  -C N_CLUSTERS, --n_clusters N_CLUSTERS
                        Number of clusters for Drain to organize log chunks into. This only makes sense when you are summarizing with Drain
  -v, --verbose
  -q, --quiet
```

```
  Installing       : llama-cpp-b3561-1.fc40.x86_64
  Installing       : python3-llama-cpp-python-0.2.87-1.fc40.x86_64
  Installing       : python3-logdetective-0.2.5-1.fc40.noarch
```
